=== karnsaurabh/BMC-CMDB-INTG/column/model/CMDBXMLSchema1111.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="CMDB" type="cmdb"/>

  <xs:complexType name="cmdb">
    <xs:sequence>
      <xs:element name="constantData" type="custConstantData" minOccurs="0"/>
      <xs:element name="classDataList" type="custClassData" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="custConstantData">
    <xs:sequence>
      <xs:element name="custDatasetId" type="xs:string" minOccurs="0"/>
      <xs:element name="custFirstRetrieve" type="xs:int"/>
      <xs:element name="custGetMask" type="xs:string" minOccurs="0"/>
      <xs:element name="custMaxRetrieve" type="xs:int"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="custClassData">
    <xs:sequence>
      <xs:element name="custAttributes" type="custAttributes" minOccurs="0"/>
      <xs:element name="custClassNameId" type="custClassNameId" minOccurs="0"/>
      <xs:element name="custQuery" type="xs:string" minOccurs="0"/>
      <xs:element name="custSortOrder" type="custSortOrder" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:int" use="required"/>
  </xs:complexType>

  <xs:complexType name="custAttributes">
    <xs:sequence>
      <xs:element name="custList" type="xs:string" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="custClassNameId">
    <xs:sequence>
      <xs:element name="custClassName" type="xs:string" minOccurs="0"/>
      <xs:element name="custNamespaceName" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="custSortOrder">
    <xs:sequence>
      <xs:element name="sortOrderlist" type="custSortOrderAttributes" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="custSortOrderAttributes">
    <xs:sequence>
      <xs:element name="attributeName" type="xs:string" minOccurs="0"/>
      <xs:element name="sortOrder" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== karnsaurabh/BMC-CMDB-INTG/xml_resources/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<CMDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../src/com/column/model/CMDBXMLSchema1111.xsd">
<constantData>
    <custDatasetId>SCCM.IMPORT</custDatasetId>
	<custFirstRetrieve>0</custFirstRetrieve>
	<custGetMask>DATASET_MODE_CURRENT</custGetMask>
	<custMaxRetrieve>0</custMaxRetrieve>
</constantData>
<classDataList id="1">
    <custAttributes>
		<custList>Name</custList>
		<custList>Description</custList>
		<custList>Region</custList>
            <custList>Site Group</custList>
            <custList>Site</custList>
            <custList>Floor</custList>
            <custList>Room</custList>
            <custList>Confidentiality</custList>
            <custList>Integrity</custList>
            <custList>Department</custList>
            <custList>OwnerName</custList>
            <custList>Serial Number</custList>
            <custList>Domain</custList> 
	</custAttributes>
    <custClassNameId>
        <custClassName>BMC_ComputerSystem</custClassName>
        <custNamespaceName>BMC.CORE</custNamespaceName>
    </custClassNameId>
    <custQuery></custQuery>
    <custSortOrder>
		<sortOrderlist>
			<attributeName>Name</attributeName>
			<sortOrder>ASENDING</sortOrder>
		</sortOrderlist>
	</custSortOrder>	
</classDataList>

<classDataList id="2">
    <custAttributes>
			<custList>Name</custList>
	</custAttributes>
    <custClassNameId>
        <custClassName>BMC_IPEndpoint</custClassName>
        <custNamespaceName>BMC.CORE</custNamespaceName>
    </custClassNameId>
    <custQuery></custQuery>
    <custSortOrder>
		<sortOrderlist>
			<attributeName>Name</attributeName>
			<sortOrder>ASENDING</sortOrder>
		</sortOrderlist>
	</custSortOrder>
</classDataList>

<classDataList id="3">
    <custAttributes>
			<custList>Name</custList>
	</custAttributes>
    <custClassNameId>
        <custClassName>BMC_LANEndpoint</custClassName>
        <custNamespaceName>BMC.CORE</custNamespaceName>
    </custClassNameId>
    <custQuery></custQuery>
    <custSortOrder>
		<sortOrderlist>
			<attributeName>Name</attributeName>
			<sortOrder>ASENDING</sortOrder>
		</sortOrderlist>
	</custSortOrder>
</classDataList>
   
</CMDB>
